version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgresdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  postgresdata:
