@id = dde9ca19-6279-4896-b03c-9040823f16a3
### CREATE BIKE
POST /api/bikes/register HTTP/1.1
Content-Type: application/json
Tenantid: 7d8a92a1-4979-4b6d-863b-c8a4cfda2c00
Host: localhost:3000
Content-Length: 2488

{
  "name": "bike",
  "type": "montanha",
  "bodySize": 1,
  "maxLoad": 1,
  "rate": 1,
  "description": "description",
  "ratings": 1,
  "imageUrls": ["http://teste.com/imagem"],
  "available": false,
  "lat": 1,
  "long": 1
}


### FIND ONE BIKE
get /api/bikes/find?id={{id}} HTTP/1.1
Content-Type: application/json
Tenantid: 7d8a92a1-4979-4b6d-863b-c8a4cfda2c00
Host: localhost:3000
Content-Length: 2488



### FIND ALL BIKES
GET /api/bikes/ HTTP/1.1
Content-Type: application/json
Tenantid: 7d8a92a1-4979-4b6d-863b-c8a4cfda2c00
Host: localhost:3000
Content-Length: 2488

### DELETE BIKE
DELETE /api/bikes/remove?id={{id}} HTTP/1.1
Content-Type: application/json
Tenantid: 7d8a92a1-4979-4b6d-863b-c8a4cfda2c00
Host: localhost:3000
Content-Length: 2488

